################################################################################
#
# Title:        ONTAP-35-02 NVMe - Volumes
# Author:       NetApp Inc. (ken)
# Initial 
# Create Date:  2023-10-11
# Description:  NVMe
#               - Volumes
#
# URLs:         https://docs.netapp.com/us-en/ontap/index.html
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.<module_name>
# 
################################################################################

- hosts:              "{{ global_primary_test_cluster }}"
  name:               "ONTAP-35-02 - Volumes"
  gather_facts:       false
  vars:
    input: &input
      hostname:                   "{{ ansible_host }}"
      username:                   "{{ ontap_admin_user }}"
      password:                   "{{ ontap_admin_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   "always"
  vars_files:
    - ../vars/labondemand/vars.yml
    - ../vars/labondemand/vault.yml
  collections:
    - netapp.ontap

  pre_tasks:

  tasks:
    - name: Create volume
      netapp.ontap.na_ontap_volume:
        state:                      present
        name:                       "{{ ontap_35_vol_name }}"
        aggregate_name:             "{{ hostvars[global_primary_test_cluster].storage_aggregates[0].name }}"
        size:                       "{{ ontap_default_vol_size_gb }}"
        size_unit:                  gb
        space_guarantee:            none
        tiering_policy:             auto
        export_policy:              "ro_{{ global_primary_nas_svm }}"
        junction_path:              "/{{ ontap_35_vol_name }}"
        vserver:                    "{{ global_primary_san_svm }}"
        volume_security_style:      "unix"
        <<: *input
  
  post_tasks: